### ISSUE TITLE
Not able to get the fixation data after code execution

### ISSUE THREAD

**Issue by asaatif** [uxifiit/GazeToolkit#23]
I have a CSV file which has Tobii eye-tracker data (using as a sample file). It looks something like this
![Screenshot (36)](https://user-images.githubusercontent.com/100682518/156146312-3c277872-9d4a-4e6d-b67a-66fdf614c2a2.png)
.
The data is in the same format as described in the Readme file of this project. 

I am executing the following line in the command window. myData1.csv is my input file with raw eye gaze data and fixations.csv is where I want to write the fixations.
i-vt.exe D:\myData1.csv --format CSV --timestamp-format ticks:us --fillin --select Average --denoise --denoise-alpha 0.3 --frequency 300 --threshold 30 --merge --merge-max-gap 75 --discard --discard-min-duration 60 --output-format CSV --output D:\fixations.csv

After the code execution, the output file is simply blank with only the header. No data is there.
![Screenshot (40)](https://user-images.githubusercontent.com/100682518/156147437-1f4d1b58-f542-43b9-800f-a695a626e3c7.png)

Here is the terminal view after the execution of code:
![Screenshot (38)](https://user-images.githubusercontent.com/100682518/156146846-9d83b83b-1add-4bfa-a44e-ae39ee6e1d75.png)

Can you please suggest if I am doing something wrong? 

I have also tried pipeline code execution as described here: https://github.com/uxifiit/GazeToolkit/issues/18

Kindly help me out of this
Thanks

**Comment by martinkonopka** [comment]
I can take a look at it.

Could you, please, attach the sample file here? Or try it with smaller sample, not the whole recording, and if it behaves the same, share the smaller file here (to not expose your whole data file).

**Comment by martinkonopka** [comment]
I tried it with sample of my data recorded with Tobii TX-300 (300Hz frequency). I attach files with timestamps both in microsecond ticks and date string. I use the same command as you and I get the desired output:

Input files:
* [input_ticks-us.csv](https://github.com/uxifiit/GazeToolkit/files/8173490/input_ticks-us.csv)
* [input_date.csv](https://github.com/uxifiit/GazeToolkit/files/8173493/input_date.csv)

Commands for each file:
```
# with timestamps in microsecond ticks format
i-vt.exe input_ticks-us.csv --format CSV --timestamp-format ticks:us --fillin --select Average --denoise --denoise-alpha 0.3 --frequency 300 --threshold 30 --merge --merge-max-gap 75 --discard --discard-min-duration 60 --output-format CSV --output output.csv

# with timestamps in date format
i-vt.exe input_date.csv --format CSV --timestamp-format date --fillin --select Average --denoise --denoise-alpha 0.3 --frequency 300 --threshold 30 --merge --merge-max-gap 75 --discard --discard-min-duration 60 --output-format CSV --output output.csv
```

Contents of the `output.csv` for [input_ticks-us.csv](https://github.com/uxifiit/GazeToolkit/files/8173490/input_ticks-us.csv):
```
Timestamp,MovementType,Duration,AverageGazePoint2DX,AverageGazePoint2DY,AverageGazePoint3DX,AverageGazePoint3DY,AverageGazePoint3DZ,AverageEyePosition3DX,AverageEyePosition3DY,AverageEyePosition3DZ,AveragePupilDiameter
63665708848005210,Fixation,2554.597,0.103680339429494,0.0941844370227761,-203.629041780781,279.632641473214,99.8095474757076,-4.71131461528727,-33.8008176905819,716.311789893637,5.84596384810406
63665708850559807,Saccade,23.338,,,,,,,,,
63665708850583145,Unknown,23.335,,,,,,,,,
63665708850606480,Saccade,16.657,,,,,,,,,
63665708850623137,Fixation,493.25,0.094186489905852,0.0736467710294352,-208.506982085741,285.151113172496,102.046920487909,-4.00790992971969,-33.864278925102,715.691972009477,5.9727451221363
63665708851116387,Saccade,36.67,,,,,,,,,
63665708851153057,Fixation,219.966,0.105584509578021,0.21466137756897,-202.650678411805,247.260489271711,86.6847894288956,-3.74999011040187,-34.404844331504,715.135778873439,5.81960608742454
63665708851373023,Saccade,49.99,,,,,,,,,
63665708851423013,Unknown,39.995,,,,,,,,,
63665708851463008,Saccade,6.612,,,,,,,,,
63665708851469620,Unknown,13.387,,,,,,,,,
63665708851483007,Saccade,6.665,,,,,,,,,
63665708851489672,Unknown,1.672,,,,,,,,,
```

Do you have data recorded with 300Hz frequency? Because you set the data frequency to that value with argument `--frequency 300`.

**Comment by asaatif** [comment]
Thanks a lot for quick reply. I checked your example in my system and it works well. I found out my mistake. I did not recognize that my timestamps are constant. Now, it is sorted out, I corrected it and found the and able to obtain fixations. 
[fixationIVT.csv](https://github.com/uxifiit/GazeToolkit/files/8176728/fixationIVT.csv)


Once again Thanks

**Comment by martinkonopka** [comment]
I am glad you sorted it out. Yes, the timestamps are needed.
